repos:
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        name: Format code
        additional_dependencies: ["toml>=0.10.2"]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Sort imports

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        name: Check PEP8
  
  - repo: local
    hooks:
      - id: mypy
        name: Check mypy
        entry: mypy --namespace-packages -p camel -p test -p apps
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true

  - repo: local
    hooks:
    - id: check-license
      name: Check License
      entry: python licenses/update_license.py . licenses/license_template.txt 
      language: system
      types: [python]